Profile shashi
CodingNinjasCodes/wall-of-developers pull request #62
Opened 2020-04-14 08:21 UTC by shashiBhushan13

Add my resume to your folder

2020-04-14 18:14 UTC, dakshkhetan requested changes

2020-04-14 18:14 UTC, dakshkhetan commented on batches/2020/career-camp-06-january-2020/index.html
> +                <br><small class="small-font grey ">.</small>
Please add a mini-bio (refer other cards) in place of dot (.)

2020-04-16 16:41 UTC, shashiBhushan13 commented
Added mini-bio,merge it please

2020-04-16 17:08 UTC, dakshkhetan requested changes
I guess you haven't pushed the commits. Please do that. As there is still a . (dot) appearing in your mini-bio in this PR.

2020-04-17 12:59 UTC, dakshkhetan commented
Closing this PR due to no response.
Raise a new one with requested changes done.

2020-04-17 12:59 UTC, closed without merging